[package]
name = "esp32-hall-servo"
version = "0.1.0"
authors = ["Derek Song"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
esp-hal = { version = "0.20", features = ["esp32"] }
esp-backtrace = { version = "0.14", features = [
    "esp32",
    "exception-handler",
    "panic-handler",
    "println",
] }
esp-println = { version = "0.11", features = ["esp32"] }

[profile.dev]
opt-level = "z"
debug = true
lto = false

[profile.release]
opt-level = "z"
debug = false
lto = "fat"
strip = true
codegen-units = 1